#! /bin/bash

# Suppression de ack
rm -f $HOME/.ack > /dev/null 2>&1 || true

grep $USER /etc/passwd | cut -d ":" -f 7 | grep zsh > /dev/null 2>&1 || {
    grep -E "\.bin" $HOME/.profile 2> /dev/null 2>&1 && exit 0

cat >> $HOME/.profile <<EOF

# set PATH so it includes user's private .bin if it exists
if [ -d "\$HOME/.bin" ] ; then
        PATH="\$HOME/.bin:\$PATH"
fi
EOF
}

if [ -e "$HOME/.zshenv" ] ; then
    grep -E "\.bin" $HOME/.zshenv > /dev/null 2>&1 && exit 0
fi

cat >> $HOME/.zshenv <<EOF
export PATH="\$HOME/.bin:\$PATH"
EOF
