#! /bin/bash

grep -E "\.bin" $HOME/.profile 2> /dev/null 2>&1 && exit 0

cat >> $HOME/.profile <<EOF

# set PATH so it includes user's private .bin if it exists
if [ -d "$HOME/.bin" ] ; then
        PATH="$HOME/.bin:$PATH"
fi
EOF
