#! /bin/bash

sudo apt-get install task

hostname | grep jones > /dev/null 2>&1 && TASKS_DIR="$HOME/taskwarrior" || TASKS_DIR="/srv/users/$USER/taskwarrior"

install -d ${TASKS_DIR}
cd $HOME && ln -sf $TASKS_DIR .tasks > /dev/null 2>&1 | true

exit
