#! /bin/bash

sudo apt-get install task


[ -d "$HOME/.task" ] || {
    hostname | grep jones > /dev/null 2>&1 && TASKS_DIR="$HOME/taskwarrior"

    install -d ${TASKS_DIR}
    cd $HOME && ln -sf $TASKS_DIR .task > /dev/null 2>&1 | true
}

exit 0
