#! /bin/bash

cd $HOME
git config --global user.name "Stéphane GAUTIER"
git config --global user.email educatux@gmail.com

git config --global alias.st status
git config --global alias.ci commit
git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.glog 'log --oneline --decorate'

git config --global color.branch auto
git config --global color.diff auto
git config --global color.interactive auto
git config --global color.status auto

git config --global push.default upstream
