#! /bin/bash

git config -f $HOME/.gitconfig user.name "Stéphane GAUTIER"
git config -f $HOME/.gitconfig user.email educatux@gmail.com

git config -f $HOME/.gitconfig alias.st status
git config -f $HOME/.gitconfig alias.ci commit
git config -f $HOME/.gitconfig alias.co checkout
git config -f $HOME/.gitconfig alias.br branch
git config -f $HOME/.gitconfig alias.glog 'log --oneline --decorate'

git config -f $HOME/.gitconfig color.branch auto
git config -f $HOME/.gitconfig color.diff auto
git config -f $HOME/.gitconfig color.interactive auto
git config -f $HOME/.gitconfig color.status auto
