#! /bin/bash

#echo -n "Password: "
#stty -echo
#read PASSWORD
#stty echo
#echo
#

[[ "$SHELL" = "/bin/zsh" ]] || {
    read -s -p "Enter Password: " PASSWORD
    echo
    echo $PASSWORD | chsh -s /bin/zsh > /dev/null 2>&1
}

