#! /bin/bash

#echo -n "Password: "
#stty -echo
#read PASSWORD
#stty echo
#echo
#


grep $USER /etc/passwd | cut -d ':' -f 7 | grep zsh > /dev/null 2>&1 || {
    echo
    read -s -p "Enter Password: " PASSWORD
    echo
    echo $PASSWORD | chsh -s /bin/zsh > /dev/null 2>&1
}

